source "https://rubygems.org"

group :test do
  gem "rake"
  gem "puppet", '4.2.2'
  gem "rspec"
  gem "rspec-puppet"
  gem 'puppetlabs_spec_helper', :git => 'https://github.com/isaiahfrantz/puppetlabs_spec_helper'
  gem "metadata-json-lint"
  gem "rspec-puppet-facts"
  gem "rspec-puppet-utils"
  gem 'rubocop'
  gem 'simplecov'
  gem 'simplecov-console'

  gem "puppet-lint-absolute_classname-check"
  gem "puppet-lint-leading_zero-check"
  gem "puppet-lint-trailing_comma-check"
  gem "puppet-lint-version_comparison-check"
  gem "puppet-lint-classes_and_types_beginning_with_digits-check"
  gem "puppet-lint-unquoted_string-check"
end

group :development do
  gem "puppet-blacksmith"
  gem "guard-rake"
end

group :system_tests do
  gem "beaker"
  gem "beaker-rspec"
  gem "beaker-puppet_install_helper"
end
